Remove unused pin + upgrade yarn deps
without the yarn upgrade, I get this error:
```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
```